version: "3.9"

services:
  cookbe:
    build: .
    ports:
      - 8080:8080
  postgresql:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=cooking
      - POSTGRES_DB=cooking
